### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by emogg** [ManiacalLabs/ESPSerialWiFiManager#11]
This library works well for me, but I would like to get rid of the following warnings under platformio:

GCC
warning
extra tokens at end of #endif directive [enabled by default]at line 117 col 8 in .piolibdeps/ESPSerialWiFiManager/src/ESPSerialWiFiManager.h
GCC
warning
ignoring packed attribute because of unpacked non-POD field 'IPAddress <anonymous struct>::ip' [enabled by default]at line 53 col 15 in .piolibdeps/ESPSerialWiFiManager/src/ESPSerialWiFiManager.h
GCC
warning
ignoring packed attribute because of unpacked non-POD field 'IPAddress <anonymous struct>::gateway' [enabled by default]at line 54 col 15 in .piolibdeps/ESPSerialWiFiManager/src/ESPSerialWiFiManager.h
GCC
warning
ignoring packed attribute because of unpacked non-POD field 'IPAddress <anonymous struct>::subnet' [enabled by default]at line 55 col 15 in .piolibdeps/ESPSerialWiFiManager/src/ESPSerialWiFiManager.h
GCC
warning
ignoring packed attribute because of unpacked non-POD field 'IPAddress <anonymous struct>::dns1' [enabled by default]at line 56 col 15 in .piolibdeps/ESPSerialWiFiManager/src/ESPSerialWiFiManager.h
GCC
warning
ignoring packed attribute because of unpacked non-POD field 'IPAddress <anonymous struct>::dns2' [enabled by default]at line 57 col 15 in .piolibdeps/ESPSerialWiFiManager/src/ESPSerialWiFiManager.h

**Comment by adammhaile** [comment]
Not really familiar with platformio... that is unfortunate that it seems to not correctly handle packed structures. Mainly because it will likely not work correctly without that struct being correctly packed. Will see if I can figure out why.

**Comment by emogg** [comment]
No problem for me really because every thing works as advertised anyway. Thanks for the library.
