### ISSUE TITLE
Invalid entry on network scan informs user of invalid entry, then scans again. 

### ISSUE THREAD

**Issue by haooken** [ManiacalLabs/ESPSerialWiFiManager#4]
Should it scan again, or just reprint the network list and re-prompt (since there is an option presented to re-scan)?

**Comment by adammhaile** [comment]
I rescan because normal WiFi managers usually update live while you look at
the list since it might change. So I figured just auto rescan. But yeah...
see what you mean. In the case of invalid, yeah, just show the list again.
