### ISSUE TITLE
Prompt to commit changes before quitting

### ISSUE THREAD

**Issue by haooken** [ManiacalLabs/ESPSerialWiFiManager#5]
Should there be a prompt to commit changes before quitting? Possible to detect if any changes were made and only prompt then? Otherwise, when 6: Quit is selected, prompt: 

```
Did you remember to commit any changes to EEPROM?
1: Yes, quit
2: No, Commit Changes and Quit
3: No, Return to Main Menu
```

**Comment by adammhaile** [comment]
Ahh...brilliant. Easy enough to just detect if the changes are not
persisted and prompt before quit. Will add.
